apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnpg:aggregate-to-crossplane
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - clusters
  - clusters/status
  - backups
  - backups/status
  - scheduledbackups
  - scheduledbackups/status
  - poolers
  - poolers/status
  verbs:
  - "*"
- apiGroups:
  - barmancloud.cnpg.io
  resources:
  - objectstores
  - objectstores/status
  verbs:
  - "*"
